ARG BASE_VERSION
ARG BASE=ascend-toolkit:$BASE_VERSION
FROM $BASE

WORKDIR /tmp
COPY . ./

SHELL ["/bin/bash", "-c"]

# 设置运行用户和工作目录
USER root
WORKDIR /root/

# 安装miniconda、设置pip源和写入环境变量
RUN wget -U NoSuchBrowser/1.0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py39_24.3.0-0-Linux-aarch64.sh && \
    bash Miniconda3-py39_24.3.0-0-Linux-aarch64.sh -b -p /root/miniconda3 && \
    rm -rf Miniconda3-*.sh

ENV PATH=/root/miniconda3/bin:$PATH

# 部署pytorch2.1.0_python3.9版本的conda环境
RUN conda init && \
    conda create -n pytorch2.1.0_py39 python=3.9 -y && \
    echo 'export HF_ENDPOINT=https://hf-mirror.com' >> ~/.bashrc && \
    echo 'source /usr/local/Ascend/ascend-toolkit/set_env.sh' >> ~/.bashrc && \
    echo 'conda activate pytorch2.1.0_py39' >> ~/.bashrc

ENV PATH=/root/miniconda3/envs/pytorch2.1.0_py39/bin:$PATH

#切换为登录模式，使配置文件生效
SHELL ["/bin/bash", "--login", "-c"]
# 设定为在pytorch2.1.0_py39的conda环境中执行余下的RUN命令
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \
    pip3 install pip -U && \
    pip3 install torch==2.1.0 && \
    pip3 install numpy && \
    pip3 install absl-py attrs cloudpickle decorator jinja2 psutil scipy synr==0.5.0 tornado && \
    wget https://gitee.com/ascend/pytorch/releases/download/v5.0.0-pytorch2.1.0/torch_npu-2.1.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl && \
    pip3 install torch_npu-2.1.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl && \
    wget https://gitee.com/chinasuv/ascend-apex_torch/raw/master/apex_torch_2.1.0/apex-0.1_ascend-cp39-cp39-linux_aarch64.whl && \
    pip3 install apex-0.1_ascend-cp39-cp39-linux_aarch64.whl && \
    rm -rf ~/.cache/pip && \
    rm -rf  torch_npu*.whl apex-*.whl